import type {
  SiteSettings,
  Testimonial,
  FaqItem,
  Industry,
  ProductCategory,
  Product,
} from "@/types";
import { BRAND, PRIMARY_NAV, FOOTER_NAV } from "@/lib/constants";

export const siteSettings: SiteSettings = {
  siteName: BRAND.siteName,
  legalName: BRAND.legalName,
  tagline: BRAND.tagline,
  address: BRAND.address,
  email: BRAND.email,
  officeLandline: BRAND.officeLandline,
  officeLandlineTel: BRAND.officeLandlineTel,
  phoneMarketing1: BRAND.phoneMarketing1,
  phoneMarketing2: BRAND.phoneMarketing2,
  mainNav: PRIMARY_NAV,
  footerNav: [
    ...FOOTER_NAV.company,
    ...FOOTER_NAV.resources,
    ...FOOTER_NAV.legal,
  ],
  defaultSeo: {
    metaTitle: "CV Caltic Baru | Hotel Amenities & Linen Manufacturer Indonesia",
    metaDescription:
      "CV Caltic Baru manufactures and supplies hotel amenities, linen, and guest room accessories across Indonesia. OEM production, private label, and bulk hospitality procurement.",
  },
};

// ---------------------------------------------------------------------------
// PRODUCT CATEGORIES
// ---------------------------------------------------------------------------

export const productCategories: ProductCategory[] = [
  {
    _id: "cat-guest-room-amenities",
    title: "Guest Room Amenities",
    slug: "guest-room-amenities",
    shortDescription:
      "Shampoo, conditioner, soap, body wash, dental kits, shaving kits, vanity sets, and slippers, produced under your own brand.",
    description:
      "Guest room amenities are the products a guest interacts with most directly, which makes consistent quality and packaging important. We manufacture bathroom and bedroom amenity items in-house, from bottled liquids to individually wrapped kits, and produce them under your property's own labeling.",
    coverImage: { asset: { url: "/images/categories/guest-room-amenities.jpg" }, alt: "Guest room amenity set on a bathroom counter" },
    bannerImage: { asset: { url: "/images/categories/guest-room-amenities.jpg" }, alt: "Guest room amenity set on a bathroom counter" },
    seo: {
      metaTitle: "Hotel Guest Room Amenities Manufacturer | CV Caltic Baru",
      metaDescription:
        "Custom hotel amenities including shampoo, soap, dental kits, and slippers, manufactured in Indonesia with private label and OEM options.",
      keywords: ["hotel amenities supplier indonesia", "guest room amenities", "custom hotel amenities"],
    },
  },
  {
    _id: "cat-bedding-linen",
    title: "Bedding & Linen",
    slug: "bedding-linen",
    shortDescription:
      "Pillows, pillow cases, protectors, bolsters, cushions, and bed linen manufactured to hospitality specifications.",
    description:
      "Bedding is produced to consistent measurements and material standards across every order, so guest rooms stay uniform whether a property orders 50 pieces or 5,000. Pillows are available in multiple sizes and fill types, with matching cases and protectors.",
    coverImage: { asset: { url: "/images/categories/bedding-linen.jpg" }, alt: "Folded white hotel bedding and pillows" },
    bannerImage: { asset: { url: "/images/categories/bedding-linen.jpg" }, alt: "Folded white hotel bedding and pillows" },
    seo: {
      metaTitle: "Hotel Linen Supplier Indonesia — Bedding & Pillows | CV Caltic Baru",
      metaDescription:
        "Hotel bedding and linen supplier in Indonesia. Pillows, cases, protectors, and bolsters manufactured to consistent hospitality-grade standards.",
      keywords: ["hotel linen supplier indonesia", "supplier linen hotel", "hotel bedding manufacturer"],
    },
  },
  {
    _id: "cat-fb-linen",
    title: "F&B Linen",
    slug: "fb-linen",
    shortDescription:
      "Table cloths, table skirting, chair covers, napkins, placemats, and kitchen cloths for restaurants and banquet operations.",
    description:
      "Food & beverage linen is manufactured for repeated commercial laundering without losing shape or color. Available in round, square, and fitted formats, with table skirting and chair covers sized to standard banquet furniture.",
    coverImage: { asset: { url: "/images/categories/fb-linen.jpg" }, alt: "Restaurant dining room table setting" },
    bannerImage: { asset: { url: "/images/categories/fb-linen.jpg" }, alt: "Restaurant dining room table setting" },
    seo: {
      metaTitle: "Restaurant & Banquet Linen Supplier Indonesia | CV Caltic Baru",
      metaDescription:
        "Table cloths, chair covers, napkins, and table skirting manufactured for hotels, restaurants, and event venues in Indonesia.",
      keywords: ["restaurant linen supplier", "banquet linen indonesia", "fb linen manufacturer"],
    },
  },
  {
    _id: "cat-bathroom-amenities",
    title: "Bathroom Amenities",
    slug: "bathroom-amenities",
    shortDescription:
      "Towels, bathrobes, bath mats, and bathroom accessories produced in a range of weights and finishes.",
    description:
      "Towels and bathrobes are manufactured in multiple gsm weights and finishes to match different property positioning, from efficient day-to-day stock to heavier options for suite categories.",
    coverImage: { asset: { url: "/images/categories/bathroom-amenities.jpg" }, alt: "Bathroom counter with towels and amenities" },
    bannerImage: { asset: { url: "/images/categories/bathroom-amenities.jpg" }, alt: "Bathroom counter with towels and amenities" },
    seo: {
      metaTitle: "Hotel Towel & Bathrobe Supplier Indonesia | CV Caltic Baru",
      metaDescription:
        "Hotel towels, bathrobes, and bathroom accessories manufactured in Indonesia with custom embroidery and private label options.",
      keywords: ["hotel towel supplier indonesia", "hotel bathrobe manufacturer", "bathroom amenities supplier"],
    },
  },
  {
    _id: "cat-guest-accessories",
    title: "Guest Accessories",
    slug: "guest-accessories",
    shortDescription:
      "Notepads, pens, shoe shine kits, DND signs, laundry bags, and other bedroom essential accessories.",
    description:
      "Small guest accessories complete the in-room experience and are often the easiest items to brand consistently. We supply stationery, shoe care items, do-not-disturb signage, and similar accessories with logo printing available.",
    coverImage: { asset: { url: "/images/categories/guest-accessories.jpg" }, alt: "Branded hotel notepad and pen" },
    bannerImage: { asset: { url: "/images/categories/guest-accessories.jpg" }, alt: "Branded hotel notepad and pen" },
    seo: {
      metaTitle: "Hotel Guest Room Accessories Supplier | CV Caltic Baru",
      metaDescription:
        "Hotel guest accessories including notepads, pens, shoe shine kits, and DND signage, custom branded and supplied in bulk.",
      keywords: ["hotel guest accessories", "hotel stationery supplier", "custom hotel accessories"],
    },
  },
  {
    _id: "cat-packaging-disposables",
    title: "Packaging & Disposables",
    slug: "packaging-disposables",
    shortDescription:
      "Amenity pouches, liquid dispensers, trash bags, and packaging formats used across our product lines.",
    description:
      "Packaging is manufactured to match each product line and can be adapted to a client's branding, from printed kraft paper sleeves to soft plastic pouches and refillable liquid dispensers.",
    coverImage: { asset: { url: "/images/categories/packaging-disposables.jpg" }, alt: "Warehouse shelving stacked with packaged linen" },
    bannerImage: { asset: { url: "/images/categories/packaging-disposables.jpg" }, alt: "Warehouse shelving stacked with packaged linen" },
    seo: {
      metaTitle: "Hotel Amenity Packaging Supplier Indonesia | CV Caltic Baru",
      metaDescription:
        "Custom hotel amenity packaging, liquid dispensers, and disposables manufactured and supplied by CV Caltic Baru.",
      keywords: ["hotel amenity packaging", "liquid dispenser supplier", "hospitality packaging indonesia"],
    },
  },
];

// ---------------------------------------------------------------------------
// SAMPLE PRODUCTS (a representative product per category — expand freely in the CMS)
// ---------------------------------------------------------------------------

export const products: Product[] = [
  {
    _id: "prod-refill-liquid-shampoo",
    title: "Refill Liquid",
    slug: "refill-liquid-shampoo",
    categorySlug: "guest-room-amenities",
    categoryTitle: "Guest Room Amenities",
    shortDescription: "Bulk refill liquid for shampoo, bath gel, conditioner, or body lotion dispensers.",
    fullDescription: "Bulk refill liquid for shampoo, bath gel, conditioner, or body lotion dispensers.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/refill-liquid-shampoo.png" }, alt: "Refill Liquid" },
    gallery: [{ asset: { url: "/images/products/refill-liquid-shampoo.png" }, alt: "Refill Liquid" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-round-soap",
    title: "Round Soap",
    slug: "round-soap",
    categorySlug: "guest-room-amenities",
    categoryTitle: "Guest Room Amenities",
    shortDescription: "Round guest soap available in 15g, 20g, 25g, and 40g sizes.",
    fullDescription: "Round guest soap available in 15g, 20g, 25g, and 40g sizes.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/round-soap.png" }, alt: "Round Soap" },
    gallery: [{ asset: { url: "/images/products/round-soap.png" }, alt: "Round Soap" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-shower-cap",
    title: "Shower Cap",
    slug: "shower-cap",
    categorySlug: "guest-room-amenities",
    categoryTitle: "Guest Room Amenities",
    shortDescription: "Individually wrapped shower cap available in PP and PE materials.",
    fullDescription: "Individually wrapped shower cap available in PP and PE materials.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/shower-cap.png" }, alt: "Shower Cap" },
    gallery: [{ asset: { url: "/images/products/shower-cap.png" }, alt: "Shower Cap" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-comb-kayu",
    title: "Wooden Comb",
    slug: "comb-kayu",
    categorySlug: "guest-room-amenities",
    categoryTitle: "Guest Room Amenities",
    shortDescription: "Eco-friendly wooden guest comb, an alternative to standard plastic combs.",
    fullDescription: "Eco-friendly wooden guest comb, an alternative to standard plastic combs.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/comb-kayu.png" }, alt: "Wooden Comb" },
    gallery: [{ asset: { url: "/images/products/comb-kayu.png" }, alt: "Wooden Comb" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-razor-kayu",
    title: "Wooden Razor",
    slug: "razor-kayu",
    categorySlug: "guest-room-amenities",
    categoryTitle: "Guest Room Amenities",
    shortDescription: "Disposable guest razor with a wooden handle.",
    fullDescription: "Disposable guest razor with a wooden handle.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/razor-kayu.png" }, alt: "Wooden Razor" },
    gallery: [{ asset: { url: "/images/products/razor-kayu.png" }, alt: "Wooden Razor" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-shaving-cream",
    title: "Shaving Cream",
    slug: "shaving-cream",
    categorySlug: "guest-room-amenities",
    categoryTitle: "Guest Room Amenities",
    shortDescription: "Travel-size shaving cream tube for guest room amenity sets.",
    fullDescription: "Travel-size shaving cream tube for guest room amenity sets.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/shaving-cream.png" }, alt: "Shaving Cream" },
    gallery: [{ asset: { url: "/images/products/shaving-cream.png" }, alt: "Shaving Cream" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-toothbrush-sikat",
    title: "Toothbrush",
    slug: "toothbrush-sikat",
    categorySlug: "guest-room-amenities",
    categoryTitle: "Guest Room Amenities",
    shortDescription: "Individually wrapped guest toothbrush, available in standard, wood, and crystal finishes.",
    fullDescription: "Individually wrapped guest toothbrush, available in standard, wood, and crystal finishes.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/toothbrush-sikat.png" }, alt: "Toothbrush" },
    gallery: [{ asset: { url: "/images/products/toothbrush-sikat.png" }, alt: "Toothbrush" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-disposable-slippers",
    title: "Disposable Slippers",
    slug: "disposable-slippers",
    categorySlug: "guest-room-amenities",
    categoryTitle: "Guest Room Amenities",
    shortDescription: "Soft disposable guest slippers in terry, velour, waffle, and non-woven fabrics.",
    fullDescription: "Soft disposable guest slippers in terry, velour, waffle, and non-woven fabrics.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/disposable-slippers.png" }, alt: "Disposable Slippers" },
    gallery: [{ asset: { url: "/images/products/disposable-slippers.png" }, alt: "Disposable Slippers" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-bed-sheet-set",
    title: "Bed Sheet Set",
    slug: "bed-sheet-set",
    categorySlug: "bedding-linen",
    categoryTitle: "Bedding & Linen",
    shortDescription: "Hotel bed sheet set styled with matching pillows and a bed runner.",
    fullDescription: "Hotel bed sheet set styled with matching pillows and a bed runner.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/bed-sheet-set.png" }, alt: "Bed Sheet Set" },
    gallery: [{ asset: { url: "/images/products/bed-sheet-set.png" }, alt: "Bed Sheet Set" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-bed-skirting",
    title: "Bed Skirting",
    slug: "bed-skirting",
    categorySlug: "bedding-linen",
    categoryTitle: "Bedding & Linen",
    shortDescription: "Fitted bed skirting that conceals the bed frame and box spring.",
    fullDescription: "Fitted bed skirting that conceals the bed frame and box spring.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/bed-skirting.png" }, alt: "Bed Skirting" },
    gallery: [{ asset: { url: "/images/products/bed-skirting.png" }, alt: "Bed Skirting" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-inner-duvet",
    title: "Inner Duvet",
    slug: "inner-duvet",
    categorySlug: "bedding-linen",
    categoryTitle: "Bedding & Linen",
    shortDescription: "Soft inner duvet insert available with a matching removable cover.",
    fullDescription: "Soft inner duvet insert available with a matching removable cover.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/inner-duvet.png" }, alt: "Inner Duvet" },
    gallery: [{ asset: { url: "/images/products/inner-duvet.png" }, alt: "Inner Duvet" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-mattress-topper",
    title: "Mattress Topper",
    slug: "mattress-topper",
    categorySlug: "bedding-linen",
    categoryTitle: "Bedding & Linen",
    shortDescription: "Quilted mattress topper for extra comfort and mattress protection.",
    fullDescription: "Quilted mattress topper for extra comfort and mattress protection.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/mattress-topper.png" }, alt: "Mattress Topper" },
    gallery: [{ asset: { url: "/images/products/mattress-topper.png" }, alt: "Mattress Topper" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-pillow",
    title: "Pillow",
    slug: "pillow",
    categorySlug: "bedding-linen",
    categoryTitle: "Bedding & Linen",
    shortDescription: "Hospitality-grade pillow available in two sizes and multiple fill options.",
    fullDescription: "Hospitality-grade pillow available in two sizes and multiple fill options.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/pillow.png" }, alt: "Pillow" },
    gallery: [{ asset: { url: "/images/products/pillow.png" }, alt: "Pillow" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-pillow-case",
    title: "Pillow Case",
    slug: "pillow-case",
    categorySlug: "bedding-linen",
    categoryTitle: "Bedding & Linen",
    shortDescription: "Matching pillow case sized for standard and large pillow formats.",
    fullDescription: "Matching pillow case sized for standard and large pillow formats.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/pillow-case.png" }, alt: "Pillow Case" },
    gallery: [{ asset: { url: "/images/products/pillow-case.png" }, alt: "Pillow Case" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-bolster",
    title: "Bolster",
    slug: "bolster",
    categorySlug: "bedding-linen",
    categoryTitle: "Bedding & Linen",
    shortDescription: "Cylindrical bolster with a removable case, available in multiple lengths.",
    fullDescription: "Cylindrical bolster with a removable case, available in multiple lengths.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/bolster.png" }, alt: "Bolster" },
    gallery: [{ asset: { url: "/images/products/bolster.png" }, alt: "Bolster" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-table-cloth-square",
    title: "Table Cloth — Square",
    slug: "table-cloth-square",
    categorySlug: "fb-linen",
    categoryTitle: "F&B Linen",
    shortDescription: "Square table cloth for restaurant and banquet tables.",
    fullDescription: "Square table cloth for restaurant and banquet tables.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/table-cloth-square.png" }, alt: "Table Cloth — Square" },
    gallery: [{ asset: { url: "/images/products/table-cloth-square.png" }, alt: "Table Cloth — Square" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-table-cloth-round",
    title: "Table Cloth — Round",
    slug: "table-cloth-round",
    categorySlug: "fb-linen",
    categoryTitle: "F&B Linen",
    shortDescription: "Round table cloth sized for standard round banquet tables.",
    fullDescription: "Round table cloth sized for standard round banquet tables.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/table-cloth-round.png" }, alt: "Table Cloth — Round" },
    gallery: [{ asset: { url: "/images/products/table-cloth-round.png" }, alt: "Table Cloth — Round" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-table-skirting-fb",
    title: "Table Skirting",
    slug: "table-skirting-fb",
    categorySlug: "fb-linen",
    categoryTitle: "F&B Linen",
    shortDescription: "Pleated table skirting for banquet and buffet table setups.",
    fullDescription: "Pleated table skirting for banquet and buffet table setups.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/table-skirting.png" }, alt: "Table Skirting" },
    gallery: [{ asset: { url: "/images/products/table-skirting.png" }, alt: "Table Skirting" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-table-runner",
    title: "Table Runner",
    slug: "table-runner",
    categorySlug: "fb-linen",
    categoryTitle: "F&B Linen",
    shortDescription: "Decorative table runner for restaurant and event table settings.",
    fullDescription: "Decorative table runner for restaurant and event table settings.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/table-runner.png" }, alt: "Table Runner" },
    gallery: [{ asset: { url: "/images/products/table-runner.png" }, alt: "Table Runner" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-chair-cover",
    title: "Chair Cover",
    slug: "chair-cover",
    categorySlug: "fb-linen",
    categoryTitle: "F&B Linen",
    shortDescription: "Fitted banquet chair cover for restaurants and event venues.",
    fullDescription: "Fitted banquet chair cover for restaurants and event venues.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/chair-cover.png" }, alt: "Chair Cover" },
    gallery: [{ asset: { url: "/images/products/chair-cover.png" }, alt: "Chair Cover" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-napkin",
    title: "Napkin",
    slug: "napkin",
    categorySlug: "fb-linen",
    categoryTitle: "F&B Linen",
    shortDescription: "F&B napkin manufactured for repeated commercial laundering.",
    fullDescription: "F&B napkin manufactured for repeated commercial laundering.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/napkin.png" }, alt: "Napkin" },
    gallery: [{ asset: { url: "/images/products/napkin.png" }, alt: "Napkin" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-placemat",
    title: "Placemat",
    slug: "placemat",
    categorySlug: "fb-linen",
    categoryTitle: "F&B Linen",
    shortDescription: "Woven placemat for restaurant and banquet table settings.",
    fullDescription: "Woven placemat for restaurant and banquet table settings.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/placemat.png" }, alt: "Placemat" },
    gallery: [{ asset: { url: "/images/products/placemat.png" }, alt: "Placemat" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-bath-towel",
    title: "Bath Towel",
    slug: "bath-towel",
    categorySlug: "bathroom-amenities",
    categoryTitle: "Bathroom Amenities",
    shortDescription: "Bath towel manufactured in multiple gsm weights for hotel bathrooms.",
    fullDescription: "Bath towel manufactured in multiple gsm weights for hotel bathrooms.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/bath-towel.png" }, alt: "Bath Towel" },
    gallery: [{ asset: { url: "/images/products/bath-towel.png" }, alt: "Bath Towel" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-hand-towel",
    title: "Hand Towel",
    slug: "hand-towel",
    categorySlug: "bathroom-amenities",
    categoryTitle: "Bathroom Amenities",
    shortDescription: "Hand towel sized for guest bathroom counters.",
    fullDescription: "Hand towel sized for guest bathroom counters.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/hand-towel.png" }, alt: "Hand Towel" },
    gallery: [{ asset: { url: "/images/products/hand-towel.png" }, alt: "Hand Towel" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-pool-towel",
    title: "Pool Towel",
    slug: "pool-towel",
    categorySlug: "bathroom-amenities",
    categoryTitle: "Bathroom Amenities",
    shortDescription: "Striped pool towel for resort and poolside use.",
    fullDescription: "Striped pool towel for resort and poolside use.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/pool-towel.png" }, alt: "Pool Towel" },
    gallery: [{ asset: { url: "/images/products/pool-towel.png" }, alt: "Pool Towel" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-bath-mat",
    title: "Bath Mat",
    slug: "bath-mat",
    categorySlug: "bathroom-amenities",
    categoryTitle: "Bathroom Amenities",
    shortDescription: "Absorbent bath mat for hotel and resort bathrooms.",
    fullDescription: "Absorbent bath mat for hotel and resort bathrooms.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/bath-mat.png" }, alt: "Bath Mat" },
    gallery: [{ asset: { url: "/images/products/bath-mat.png" }, alt: "Bath Mat" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-oshibori",
    title: "Oshibori",
    slug: "oshibori",
    categorySlug: "bathroom-amenities",
    categoryTitle: "Bathroom Amenities",
    shortDescription: "Rolled oshibori hand towels for guest welcome service.",
    fullDescription: "Rolled oshibori hand towels for guest welcome service.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/oshibori.png" }, alt: "Oshibori" },
    gallery: [{ asset: { url: "/images/products/oshibori.png" }, alt: "Oshibori" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-face-towel",
    title: "Face Towel",
    slug: "face-towel",
    categorySlug: "bathroom-amenities",
    categoryTitle: "Bathroom Amenities",
    shortDescription: "Small face towel / washcloth for guest bathrooms.",
    fullDescription: "Small face towel / washcloth for guest bathrooms.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/face-towel.png" }, alt: "Face Towel" },
    gallery: [{ asset: { url: "/images/products/face-towel.png" }, alt: "Face Towel" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-notepad-set",
    title: "Notepad Set",
    slug: "notepad-set",
    categorySlug: "guest-accessories",
    categoryTitle: "Guest Accessories",
    shortDescription: "Branded guest room notepad set with a matching pen.",
    fullDescription: "Branded guest room notepad set with a matching pen.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/notepad-set.png" }, alt: "Notepad Set" },
    gallery: [{ asset: { url: "/images/products/notepad-set.png" }, alt: "Notepad Set" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-dnd-sign",
    title: "DND Sign",
    slug: "dnd-sign",
    categorySlug: "guest-accessories",
    categoryTitle: "Guest Accessories",
    shortDescription: "Do-not-disturb door hanger sign set.",
    fullDescription: "Do-not-disturb door hanger sign set.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/dnd-sign.png" }, alt: "DND Sign" },
    gallery: [{ asset: { url: "/images/products/dnd-sign.png" }, alt: "DND Sign" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-souvenir-pen",
    title: "Souvenir Pen",
    slug: "souvenir-pen",
    categorySlug: "guest-accessories",
    categoryTitle: "Guest Accessories",
    shortDescription: "Branded souvenir pen for guest rooms and reception.",
    fullDescription: "Branded souvenir pen for guest rooms and reception.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/souvenir-pen.png" }, alt: "Souvenir Pen" },
    gallery: [{ asset: { url: "/images/products/souvenir-pen.png" }, alt: "Souvenir Pen" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-shoe-shine-kit",
    title: "Shoe Shine Kit",
    slug: "shoe-shine-kit",
    categorySlug: "guest-accessories",
    categoryTitle: "Guest Accessories",
    shortDescription: "Compact shoe shine kit for guest room amenity trays.",
    fullDescription: "Compact shoe shine kit for guest room amenity trays.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/shoe-shine-kit.png" }, alt: "Shoe Shine Kit" },
    gallery: [{ asset: { url: "/images/products/shoe-shine-kit.png" }, alt: "Shoe Shine Kit" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-hanger-kayu",
    title: "Wooden Hanger",
    slug: "hanger-kayu",
    categorySlug: "guest-accessories",
    categoryTitle: "Guest Accessories",
    shortDescription: "Standard wooden guest room hanger.",
    fullDescription: "Standard wooden guest room hanger.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/hanger-kayu.png" }, alt: "Wooden Hanger" },
    gallery: [{ asset: { url: "/images/products/hanger-kayu.png" }, alt: "Wooden Hanger" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-hanger-kayu-clip",
    title: "Wooden Hanger with Clips",
    slug: "hanger-kayu-clip",
    categorySlug: "guest-accessories",
    categoryTitle: "Guest Accessories",
    shortDescription: "Wooden hanger with stainless steel trouser clips.",
    fullDescription: "Wooden hanger with stainless steel trouser clips.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/hanger-kayu-clip.png" }, alt: "Wooden Hanger with Clips" },
    gallery: [{ asset: { url: "/images/products/hanger-kayu-clip.png" }, alt: "Wooden Hanger with Clips" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-laundry-bag",
    title: "Laundry Bag",
    slug: "laundry-bag",
    categorySlug: "guest-accessories",
    categoryTitle: "Guest Accessories",
    shortDescription: "Fabric drawstring laundry bag for guest room laundry service.",
    fullDescription: "Fabric drawstring laundry bag for guest room laundry service.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/laundry-bag.png" }, alt: "Laundry Bag" },
    gallery: [{ asset: { url: "/images/products/laundry-bag.png" }, alt: "Laundry Bag" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-garment-cover",
    title: "Garment Cover",
    slug: "garment-cover",
    categorySlug: "guest-accessories",
    categoryTitle: "Guest Accessories",
    shortDescription: "Clear garment cover for guest room wardrobes.",
    fullDescription: "Clear garment cover for guest room wardrobes.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/garment-cover.png" }, alt: "Garment Cover" },
    gallery: [{ asset: { url: "/images/products/garment-cover.png" }, alt: "Garment Cover" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-trash-bag-clear",
    title: "Trash Bag — Clear",
    slug: "trash-bag-clear",
    categorySlug: "packaging-disposables",
    categoryTitle: "Packaging & Disposables",
    shortDescription: "Heavy-duty clear trash bag in multiple sizes.",
    fullDescription: "Heavy-duty clear trash bag in multiple sizes.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/trash-bag-clear.png" }, alt: "Trash Bag — Clear" },
    gallery: [{ asset: { url: "/images/products/trash-bag-clear.png" }, alt: "Trash Bag — Clear" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-trash-bag-yellow",
    title: "Trash Bag — Yellow",
    slug: "trash-bag-yellow",
    categorySlug: "packaging-disposables",
    categoryTitle: "Packaging & Disposables",
    shortDescription: "Heavy-duty yellow trash bag in multiple sizes.",
    fullDescription: "Heavy-duty yellow trash bag in multiple sizes.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/trash-bag-yellow.png" }, alt: "Trash Bag — Yellow" },
    gallery: [{ asset: { url: "/images/products/trash-bag-yellow.png" }, alt: "Trash Bag — Yellow" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-trash-bag-black",
    title: "Trash Bag — Black",
    slug: "trash-bag-black",
    categorySlug: "packaging-disposables",
    categoryTitle: "Packaging & Disposables",
    shortDescription: "Heavy-duty black trash bag in multiple sizes.",
    fullDescription: "Heavy-duty black trash bag in multiple sizes.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/trash-bag-black.png" }, alt: "Trash Bag — Black" },
    gallery: [{ asset: { url: "/images/products/trash-bag-black.png" }, alt: "Trash Bag — Black" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-amenity-pouch",
    title: "Amenity Pouch",
    slug: "amenity-pouch",
    categorySlug: "packaging-disposables",
    categoryTitle: "Packaging & Disposables",
    shortDescription: "Drawstring amenity pouch used across our packaging lines.",
    fullDescription: "Drawstring amenity pouch used across our packaging lines.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/amenity-pouch.png" }, alt: "Amenity Pouch" },
    gallery: [{ asset: { url: "/images/products/amenity-pouch.png" }, alt: "Amenity Pouch" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-travel-bottle-set",
    title: "Travel Bottle Set",
    slug: "travel-bottle-set",
    categorySlug: "packaging-disposables",
    categoryTitle: "Packaging & Disposables",
    shortDescription: "Small refillable travel bottle set for amenity kits.",
    fullDescription: "Small refillable travel bottle set for amenity kits.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/travel-bottle-set.png" }, alt: "Travel Bottle Set" },
    gallery: [{ asset: { url: "/images/products/travel-bottle-set.png" }, alt: "Travel Bottle Set" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-box-organizer",
    title: "Box Organizer",
    slug: "box-organizer",
    categorySlug: "packaging-disposables",
    categoryTitle: "Packaging & Disposables",
    shortDescription: "Amenity box organizer set for guest room presentation.",
    fullDescription: "Amenity box organizer set for guest room presentation.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/box-organizer.png" }, alt: "Box Organizer" },
    gallery: [{ asset: { url: "/images/products/box-organizer.png" }, alt: "Box Organizer" }],
    featured: false,
    isNew: false,
  },
  {
    _id: "prod-liquid-dispenser",
    title: "Liquid Dispenser",
    slug: "liquid-dispenser",
    categorySlug: "packaging-disposables",
    categoryTitle: "Packaging & Disposables",
    shortDescription: "Refillable pump-top liquid dispenser for bulk amenity programs.",
    fullDescription: "Refillable pump-top liquid dispenser for bulk amenity programs.",
    materials: [],
    features: [],
    applications: [],
    customizationOptions: [],
    packagingOptions: [],
    coverImage: { asset: { url: "/images/products/liquid-dispenser-amber.png" }, alt: "Liquid Dispenser" },
    gallery: [{ asset: { url: "/images/products/liquid-dispenser-amber.png" }, alt: "Liquid Dispenser" }],
    featured: false,
    isNew: false,
  },
];

// ---------------------------------------------------------------------------
// INDUSTRIES SERVED
// ---------------------------------------------------------------------------

export const industries: Industry[] = [
  {
    _id: "ind-hotels-resorts",
    title: "Hotels & Resorts",
    slug: "hotels-resorts",
    summary: "Guest room amenities, bedding, and linen supplied at chain scale or single-property volume.",
    description:
      "Hotels and resorts make up the largest share of our manufacturing output. We supply everything from bathroom amenities to bedding and F&B linen, produced under the property's own brand and delivered on schedules that match housekeeping and procurement cycles.",
    relatedCategorySlugs: ["guest-room-amenities", "bedding-linen", "bathroom-amenities"],
  },
  {
    _id: "ind-villas-serviced-apartments",
    title: "Villas & Serviced Apartments",
    slug: "villas-serviced-apartments",
    summary: "Smaller-batch orders with the same manufacturing standards used for larger hotel groups.",
    description:
      "Villas and serviced apartments often need lower order volumes without a drop in consistency. Our production planning accommodates smaller, recurring orders alongside our larger hotel contracts.",
    relatedCategorySlugs: ["guest-room-amenities", "bedding-linen", "guest-accessories"],
  },
  {
    _id: "ind-restaurants-cafes",
    title: "Restaurants & Cafés",
    slug: "restaurants-cafes",
    summary: "F&B linen, table setup textiles, and branded service accessories.",
    description:
      "Restaurants and cafés rely on us for table linen that holds up to daily commercial laundering, along with service accessories that can carry consistent branding across multiple outlets.",
    relatedCategorySlugs: ["fb-linen", "guest-accessories"],
  },
  {
    _id: "ind-hospitals",
    title: "Hospitals",
    slug: "hospitals",
    summary: "Patient room linen and amenities produced to consistent hygiene-grade standards.",
    description:
      "Hospitals require linen and amenity products with predictable quality and supply continuity. We manufacture to the same inspection standards used across our hospitality lines and support recurring bulk procurement schedules.",
    relatedCategorySlugs: ["bedding-linen", "bathroom-amenities"],
  },
  {
    _id: "ind-commercial-buildings",
    title: "Commercial Buildings",
    slug: "commercial-buildings",
    summary: "Guest and staff amenities, cleaning-adjacent disposables, and packaging for mixed-use properties.",
    description:
      "Commercial developments with guest-facing or residential components use our amenity and packaging lines to furnish common areas and guest suites at scale.",
    relatedCategorySlugs: ["guest-accessories", "packaging-disposables"],
  },
  {
    _id: "ind-hospitality-groups",
    title: "Hospitality Groups",
    slug: "hospitality-groups",
    summary: "Multi-property procurement, private label programs, and standardized amenity specifications across a portfolio.",
    description:
      "Hospitality groups managing multiple properties use us as a single manufacturing partner to standardize amenity specifications across their portfolio, while still allowing property-level branding variations where needed.",
    relatedCategorySlugs: ["guest-room-amenities", "bedding-linen", "fb-linen"],
  },
  {
    _id: "ind-government-projects",
    title: "Government Projects",
    slug: "government-projects",
    summary: "Bulk procurement for accommodation and institutional facilities, supplied against project specifications.",
    description:
      "Government-linked accommodation and institutional projects are supplied against defined technical specifications, with documentation to support procurement and tender requirements.",
    relatedCategorySlugs: ["bedding-linen", "guest-room-amenities"],
  },
];

// ---------------------------------------------------------------------------
// TESTIMONIALS
// ---------------------------------------------------------------------------

export const testimonials: Testimonial[] = [
  {
    _id: "test-dafam-semarang",
    quote:
      "We've been genuinely satisfied using Caltic Baru's room amenities across several rooms at our hotel. From the start, their team has been responsive and easy to work with. The material and finishing met our expectations and gave our rooms a clean, modern look, at pricing that compares well against similar products in the market. We would recommend them to anyone looking for a reliable amenities supplier.",
    clientName: "Hotel Dafam Semarang",
    clientOrganization: "Hotel Dafam Semarang",
  },
];

// ---------------------------------------------------------------------------
// FAQ
// ---------------------------------------------------------------------------

export const faqs: FaqItem[] = [
  {
    _id: "faq-moq",
    question: "What is your minimum order quantity?",
    answer:
      "Minimum order quantities vary by product and format — for example, bottled amenities and linen have different MOQs. Share your product list and target volume through the quotation form and we'll confirm MOQs for each item.",
    category: "Ordering",
  },
  {
    _id: "faq-oem",
    question: "Can you manufacture products under our own brand?",
    answer:
      "Yes. OEM and private label production is a core part of our business. We can produce existing catalogue items under your label, or develop a product to your specification from a brief and reference samples.",
    category: "OEM & Private Label",
  },
  {
    _id: "faq-samples",
    question: "Do you provide samples before a full production run?",
    answer:
      "Yes. Pre-production samples are provided for review and approval before full manufacturing begins, as part of our standard quality assurance process.",
    category: "Quality",
  },
  {
    _id: "faq-lead-time",
    question: "What are your typical lead times?",
    answer:
      "Lead times depend on product type, customization level, and order volume. We confirm a specific lead time in writing at the quotation stage, before production begins.",
    category: "Ordering",
  },
  {
    _id: "faq-industries",
    question: "Which industries do you supply?",
    answer:
      "We supply hotels, resorts, villas, serviced apartments, restaurants, cafés, hospitals, commercial buildings, hospitality groups, and government projects.",
    category: "General",
  },
  {
    _id: "faq-customization",
    question: "How does product customization work?",
    answer:
      "Customization can include material, size, scent, color, packaging format, and branding (printed, embroidered, or debossed logos). Options vary by product — our team will confirm what's available for each item you're interested in.",
    category: "Customization",
  },
  {
    _id: "faq-shipping",
    question: "Do you deliver outside Yogyakarta?",
    answer:
      "Yes, we supply hospitality businesses and procurement teams across Indonesia. Delivery method and timeline are confirmed based on your location and order volume.",
    category: "Ordering",
  },
  {
    _id: "faq-catalogue",
    question: "How can I get your full product catalogue?",
    answer:
      "You can request the full catalogue PDF on our Catalogue page, or contact our marketing team directly for a copy along with a quotation for your specific requirements.",
    category: "General",
  },
];
