import { defineField, defineType } from "sanity";

export default defineType({
  name: "product",
  title: "Product",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "media", title: "Media" },
    { name: "details", title: "Details" },
    { name: "relations", title: "Related & Badges" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Product Name",
      type: "string",
      group: "content",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "content",
      options: { source: "title" },
      description: "Used in the URL, e.g. /products/hotel-linen/premium-bath-towel",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "productCode",
      title: "Product Code (SKU)",
      type: "string",
      group: "content",
      description: "Optional. An internal reference code, shown on the product page if set.",
    }),
    defineField({
      name: "category",
      title: "Category",
      type: "reference",
      group: "content",
      to: [{ type: "productCategory" }],
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "shortDescription",
      title: "Short Description",
      type: "text",
      group: "content",
      rows: 2,
      description: "A 1-2 sentence summary used on product cards and as the SEO fallback description.",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "fullDescription",
      title: "Full Description",
      type: "text",
      group: "content",
      rows: 6,
      description: "The main descriptive copy shown on the product page.",
      validation: (Rule) => Rule.required(),
    }),

    defineField({
      name: "coverImage",
      title: "Cover Image",
      type: "galleryImage",
      group: "media",
      description: "The main image shown on product cards and first in the gallery.",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "gallery",
      title: "Gallery Images",
      type: "array",
      group: "media",
      of: [{ type: "galleryImage" }],
      description: "Unlimited additional images. Drag items to reorder — the order here is the order shown on the page and in the lightbox.",
    }),
    defineField({
      name: "pdf",
      title: "Downloadable PDF",
      type: "file",
      group: "media",
      options: { accept: ".pdf" },
      description: "Optional. A spec sheet or datasheet visitors can download from the product page.",
    }),

    defineField({
      name: "materials",
      title: "Materials",
      type: "array",
      group: "details",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "features",
      title: "Features",
      type: "array",
      group: "details",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "applications",
      title: "Applications",
      type: "array",
      group: "details",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "customizationOptions",
      title: "Customization Options",
      type: "array",
      group: "details",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "packagingOptions",
      title: "Packaging Options",
      type: "array",
      group: "details",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "specs",
      title: "Specifications",
      type: "array",
      group: "details",
      of: [{ type: "productSpec" }],
    }),

    defineField({
      name: "featured",
      title: "Featured Product",
      type: "boolean",
      group: "relations",
      initialValue: false,
      description: "Show this product in the \"Featured Products\" section on the homepage and in category browsers.",
    }),
    defineField({
      name: "isNew",
      title: "New Product Badge",
      type: "boolean",
      group: "relations",
      initialValue: false,
      description: "Show a \"New\" badge on this product's card.",
    }),
    defineField({
      name: "relatedProducts",
      title: "Related Products (manual override)",
      type: "array",
      group: "relations",
      of: [{ type: "reference", to: [{ type: "product" }] }],
      description: "Optional. If left empty, the site automatically shows other products from the same category instead. Set this to override that automatic behavior with a specific hand-picked list.",
    }),

    defineField({ name: "seo", title: "SEO", type: "seo", group: "seo" }),
  ],
  preview: {
    select: { title: "title", subtitle: "category.title", media: "coverImage" },
  },
});
